import { Cormorant, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/navigation/Footer";
import FooterBottomBanner from "@/components/globallyUseComponents/FooterBottomBanner";
import LenisProvider from "@/components/scroll/lenis/LenisProvider";

const cormorant = Cormorant({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-cormorant",
});

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Indiefluence Garage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cormorant.variable} ${lato.variable} antialiased`}>
        {/* ✅ LENIS STARTS HERE */}
        <LenisProvider>
          {children}
        </LenisProvider>
        <Footer />
        <FooterBottomBanner />
      </body>
    </html>
  );
}
